[2025-02-21T10:15:10.876+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-21T10:15:10.886+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_to_DWH.load scheduled__2025-02-20T00:00:00+00:00 [queued]>
[2025-02-21T10:15:10.891+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_to_DWH.load scheduled__2025-02-20T00:00:00+00:00 [queued]>
[2025-02-21T10:15:10.891+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-21T10:15:10.896+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load> on 2025-02-20 00:00:00+00:00
[2025-02-21T10:15:10.903+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=319) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-21T10:15:10.905+0000] {standard_task_runner.py:72} INFO - Started process 322 to run task
[2025-02-21T10:15:10.904+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_to_DWH', 'load', 'scheduled__2025-02-20T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpjn6vfgn0']
[2025-02-21T10:15:10.908+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask load
[2025-02-21T10:15:10.916+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-21T10:15:10.940+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_to_DWH.load scheduled__2025-02-20T00:00:00+00:00 [running]> on host 327d2c65685a
[2025-02-21T10:15:10.941+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-21T10:15:10.977+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_to_DWH' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2025-02-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-20T00:00:00+00:00'
[2025-02-21T10:15:10.977+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-21T10:15:11.025+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-21T10:15:11.032+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-21T10:15:11.032+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=etl_to_DWH, task_id=load, run_id=scheduled__2025-02-20T00:00:00+00:00, execution_date=20250220T000000, start_date=20250221T101510, end_date=20250221T101511
[2025-02-21T10:15:11.086+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-21T10:15:11.095+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-21T10:15:11.096+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
